language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-fab' ]; then cd .. && eval "mv $currentfolder generator-fab" && cd generator-fab; fi

